services:
  clipboard-agrams:
    image: journery:latest
    container_name: clipboard-agrams
    restart: unless-stopped
    ports:
      - "5051:5000"
    volumes:
      - ./data:/data
    environment:
      - JOURNERY_NAME=Apoo
