services:
  clipboard:
    image: journery:latest
    container_name: clipboard
    restart: unless-stopped
    ports:
      - "5050:5000"
    volumes:
      - ./data:/data
    environment:
      - JOURNERY_NAME=Setu
